# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  api:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Install dependency
        run: yarn workspace api install
      - name: Format
        run: yarn workspace api format
      - name: Lint
        run: yarn workspace api lint
      - name: Build
        run: yarn workspace api build
      - name: Test
        run: yarn workspace api test
