name: Deploy-PPE

on:
  push:
    branches: [ main ]

env:
  DOCKERHUB_USERNAME: gapeld
  IMAGE_NAME: gapeld/bookmarkmap_api_ppe


jobs:
  api:

    runs-on: ubuntu-latest

    environment: ppe

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install dependency
        run: yarn workspace api install

      - name: Format
        run: yarn workspace api format

      - name: Lint
        run: yarn workspace api lint

      - name: Build
        run: yarn workspace api build

      - name: Test
        run: yarn workspace api test

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v1.6.0

      - name: Log into registry Docker Hub
        uses: docker/login-action@v1.12.0
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v3.6.2
        with:
          images: ${{ env.IMAGE_NAME }}
          flavor: latest=true
          tags: type=sha,format=long

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v2.8.0
        with:
          context: packages/api
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: ${{ env.IMAGE_NAME }}
          cache-to: type=inline